package:
  name: mutagen
  version: !!str 1.25.1

source:
  fn: mutagen-1.25.1.tar.gz
  url: https://pypi.python.org/packages/source/m/mutagen/mutagen-1.25.1.tar.gz
  md5: 8d7dd72c12ff0978a88ecd042da9d0a5
#  patches:
   # List any patch files here
   # - fix.patch

# build:
  #preserve_egg_dir: True
  #entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - mutagen = mutagen:main
    #
    # Would create an entry point called mutagen that calls mutagen.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python

  run:
    - python

test:
  # Python imports
  imports:
    - mutagen
    - mutagen.id3

  #commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: https://bitbucket.org/lazka/mutagen
  license:  GNU General Public License v2 (GPLv2)
  summary: 'read and write audio tags for many formats'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
